import type { Projects } from "./type";

export const initialDataProjects: Projects = [
  {
    id: 1,
    title: "Personal Web",
    status: "Done",
    priority: "P1",
    description: "Personal website with HTML & CSS",
    dueDate: new Date("2025-10-01"),
  },
  {
    id: 2,
    title: "CRM",
    status: "Done",
    priority: "P2",
    description: "Simple CRM web using Tailwind and JavaScript",
    dueDate: new Date("2025-11-01"),
  },
  {
    id: 3,
    title: "Task Management",
    status: "In Review",
    priority: "P3",
    description: "Project and task management using React",
    dueDate: new Date("2025-12-01"),
  },
  {
    id: 4,
    title: "Information API",
    status: "In Progress",
    priority: "P3",
    description: "Public API for internal information service",
    dueDate: new Date("2026-01-01"),
  },
  {
    id: 5,
    title: "Simple Ecommerce",
    status: "In Progress",
    priority: "P1",
    description: "Basic ecommerce website MVP",
    dueDate: new Date("2026-02-01"),
  },
  {
    id: 6,
    title: "Portfolio Redesign",
    status: "To Do",
    priority: "P0",
    description: "Redesign portfolio UI with modern layout",
    dueDate: new Date("2025-09-15"),
  },
  {
    id: 7,
    title: "Landing Page",
    status: "To Do",
    priority: "P4",
    description: "Marketing landing page for product launch",
    dueDate: new Date("2025-08-20"),
  },
  {
    id: 8,
    title: "Auth System",
    status: "In Progress",
    priority: "P2",
    description: "Authentication system with login and register",
    dueDate: new Date("2025-10-20"),
  },
  {
    id: 9,
    title: "Crossfit MiniApp",
    status: "To Do",
    priority: "P0",
    description: "Wechat miniapp for booking Crossfit class",
    dueDate: new Date("2025-11-15"),
  },
  {
    id: 10,
    title: "Notification Service",
    status: "In Review",
    priority: "P4",
    description: "Email and in-app notification service",
    dueDate: new Date("2026-03-01"),
  },
];
